spring:
  application:
    name: springbootdemoapplication
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: 'update'




server:
  port: 8088
  servlet:
    context-path: /api

